# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actId', models.CharField(max_length=123)),
                ('subject', models.CharField(max_length=123)),
                ('content', models.CharField(max_length=123)),
                ('beginTime', models.CharField(max_length=123)),
                ('endTime', models.CharField(max_length=123)),
                ('schema', models.CharField(max_length=123)),
                ('topicTag', models.CharField(max_length=123)),
                ('pushType', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statPosition', models.CharField(max_length=123)),
                ('img', models.CharField(max_length=123)),
                ('schema', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=123)),
                ('position', models.CharField(max_length=123)),
                ('activityList', models.ManyToManyField(to='mock.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='HotTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=123)),
                ('createTime', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=123)),
                ('duration', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=123)),
                ('producer', models.CharField(max_length=123)),
                ('name', models.CharField(max_length=123)),
                ('img', models.CharField(max_length=123)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedtopicsummary',
            name='audioAttachList',
        ),
        migrations.AddField(
            model_name='feedtopicsummary',
            name='audioAttachList',
            field=models.ManyToManyField(to='mock.FeedAudioAttach'),
        ),
        migrations.AddField(
            model_name='hottopic',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.FeedTopicSummary'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='albumList',
            field=models.ManyToManyField(related_name='album', to='mock.FeedTopicSummary'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='programList',
            field=models.ManyToManyField(to='mock.Program'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='voiceList',
            field=models.ManyToManyField(related_name='voice', to='mock.FeedTopicSummary'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contentAttach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.ContentAttach'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.FeedTopicAuthor'),
        ),
        migrations.AddField(
            model_name='feedtopicsummary',
            name='contentAttach',
            field=models.ManyToManyField(to='mock.ContentAttach'),
        ),
        migrations.AddField(
            model_name='feedtopicsummary',
            name='mediaAttach',
            field=models.ManyToManyField(to='mock.MediaAttach'),
        ),
    ]
