# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0002_auto_20161114_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=123)),
            ],
            options={
                'verbose_name': 'Mock_API',
                'verbose_name_plural': 'Mock_API',
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='contentAttach',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Carousels',
        ),
        migrations.RemoveField(
            model_name='favorite_programs',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='feedhottopicresponse',
            name='summery',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='activityList',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='albumList',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='programList',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='voiceList',
        ),
        migrations.RemoveField(
            model_name='feedtopicsummary',
            name='audioAttachList',
        ),
        migrations.RemoveField(
            model_name='feedtopicsummary',
            name='contentAttach',
        ),
        migrations.RemoveField(
            model_name='feedtopicsummary',
            name='mediaAttach',
        ),
        migrations.RemoveField(
            model_name='feedtopicsummary',
            name='shareInfo',
        ),
        migrations.RemoveField(
            model_name='feedtopicsummary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hottopic',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ContentAttach',
        ),
        migrations.DeleteModel(
            name='favorite_programs',
        ),
        migrations.DeleteModel(
            name='FeedAudioAttach',
        ),
        migrations.DeleteModel(
            name='FeedHotTopicResponse',
        ),
        migrations.DeleteModel(
            name='Feeds',
        ),
        migrations.DeleteModel(
            name='FeedTopicAuthor',
        ),
        migrations.DeleteModel(
            name='FeedTopicShareInfo',
        ),
        migrations.DeleteModel(
            name='FeedTopicSummary',
        ),
        migrations.DeleteModel(
            name='HotTopic',
        ),
        migrations.DeleteModel(
            name='MediaAttach',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
