# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_auto_20161118_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='slug',
            field=models.CharField(max_length=123),
        ),
    ]
