# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_auto_20161118_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='content',
            field=models.CharField(help_text='api json data format!', max_length=1000000086),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(help_text='API Name!', max_length=123),
        ),
        migrations.AlterField(
            model_name='api',
            name='slug',
            field=models.CharField(help_text='api endpoint !', max_length=123),
        ),
    ]
